// <auto-generated />
using System;
using Licenses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Licenses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260910235946_LeaveRequests")]
    partial class LeaveRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("licenses")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Licenses.Domain.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.Authorization.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.Authorization.RoleScopeAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IncludeDescendants")
                        .HasColumnType("boolean")
                        .HasColumnName("include_descendants");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId", "OrgUnitId", "EffectiveFromUtc")
                        .IsUnique();

                    b.ToTable("role_scope_assignments", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_role_scope_assignments_valid_period", "effective_to_utc IS NULL OR effective_to_utc > effective_from_utc");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalIdentityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_identity_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalIdentityId")
                        .IsUnique()
                        .HasFilter("external_identity_id IS NOT NULL");

                    b.ToTable("users", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.BalanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BalanceBucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("balance_bucket_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BalanceBucketId");

                    b.HasIndex("UserId", "BalanceBucketId")
                        .IsUnique();

                    b.ToTable("balance_accounts", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.BalanceBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("balance_buckets", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_balance_buckets_unit", "unit IN ('DAY')");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.BalanceLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("available_delta");

                    b.Property<Guid>("BalanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("balance_account_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<decimal>("ReservedDelta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("reserved_delta");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("BalanceAccountId", "CreatedAtUtc");

                    b.ToTable("balance_ledger_entries", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_balance_ledger_entries_non_zero", "available_delta <> 0 OR reserved_delta <> 0");

                            t.HasCheckConstraint("ck_balance_ledger_entries_type", "type IN ('GRANT','RESERVE','RELEASE','CONSUME','REFUND','ADJUSTMENT','EXPIRE')");

                            t.HasCheckConstraint("ck_balance_ledger_entries_type_semantics", "(type = 'GRANT' AND available_delta > 0 AND reserved_delta = 0) OR (type = 'RESERVE' AND available_delta < 0 AND reserved_delta > 0 AND available_delta = -reserved_delta) OR (type = 'RELEASE' AND available_delta > 0 AND reserved_delta < 0 AND available_delta = -reserved_delta) OR (type = 'CONSUME' AND available_delta = 0 AND reserved_delta < 0) OR (type = 'REFUND' AND available_delta > 0 AND reserved_delta = 0) OR (type = 'ADJUSTMENT' AND available_delta <> 0 AND reserved_delta = 0) OR (type = 'EXPIRE' AND available_delta < 0 AND reserved_delta = 0)");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeavePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AppliesToDescendants")
                        .HasColumnType("boolean")
                        .HasColumnName("applies_to_descendants");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("LeaveTypeId", "OrgUnitId")
                        .IsUnique();

                    b.ToTable("leave_policies", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_leave_policies_global_descendants_false", "org_unit_id IS NOT NULL OR applies_to_descendants = false");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeavePolicyVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowHalfDay")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_half_day");

                    b.Property<Guid?>("BalanceBucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("balance_bucket_id");

                    b.Property<bool>("ConsumesBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("consumes_balance");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DayCountMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("day_count_mode");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("LeavePolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_policy_id");

                    b.Property<decimal?>("MaximumRequestDays")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("maximum_request_days");

                    b.Property<int?>("MinimumNoticeDays")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_notice_days");

                    b.Property<string>("NoticeDayCountMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("notice_day_count_mode");

                    b.Property<string>("OverlapBehavior")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("overlap_behavior");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid?>("WorkingCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("working_calendar_id");

                    b.HasKey("Id");

                    b.HasIndex("BalanceBucketId");

                    b.HasIndex("WorkingCalendarId");

                    b.HasIndex("LeavePolicyId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("LeavePolicyId", "Status", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("leave_policy_versions", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_leave_policy_versions_balance_consistency", "(consumes_balance = true AND balance_bucket_id IS NOT NULL) OR (consumes_balance = false AND balance_bucket_id IS NULL)");

                            t.HasCheckConstraint("ck_leave_policy_versions_calendar_required_for_business_days", "((day_count_mode = 'BUSINESS_DAYS' OR notice_day_count_mode = 'BUSINESS_DAYS') AND working_calendar_id IS NOT NULL) OR (day_count_mode = 'CALENDAR_DAYS' AND notice_day_count_mode = 'CALENDAR_DAYS')");

                            t.HasCheckConstraint("ck_leave_policy_versions_day_count_mode", "day_count_mode IN ('BUSINESS_DAYS','CALENDAR_DAYS')");

                            t.HasCheckConstraint("ck_leave_policy_versions_effective_range", "effective_to IS NULL OR effective_to >= effective_from");

                            t.HasCheckConstraint("ck_leave_policy_versions_max_request_positive", "maximum_request_days IS NULL OR maximum_request_days > 0");

                            t.HasCheckConstraint("ck_leave_policy_versions_min_notice_non_negative", "minimum_notice_days IS NULL OR minimum_notice_days >= 0");

                            t.HasCheckConstraint("ck_leave_policy_versions_notice_day_count_mode", "notice_day_count_mode IN ('BUSINESS_DAYS','CALENDAR_DAYS')");

                            t.HasCheckConstraint("ck_leave_policy_versions_overlap_behavior", "overlap_behavior IN ('BLOCK','WARN','ALLOW')");

                            t.HasCheckConstraint("ck_leave_policy_versions_published_at", "(status = 'PUBLISHED' AND published_at_utc IS NOT NULL) OR (status = 'DRAFT' AND published_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_leave_policy_versions_status", "status IN ('DRAFT','PUBLISHED')");

                            t.HasCheckConstraint("ck_leave_policy_versions_version_positive", "version_number > 0");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BalanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("balance_account_id");

                    b.Property<Guid?>("BalanceReservationOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("balance_reservation_operation_id");

                    b.Property<decimal?>("CalculatedDays")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("calculated_days");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DayPortion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("day_portion");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("LeavePolicyVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_policy_version_id");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BalanceAccountId");

                    b.HasIndex("BalanceReservationOperationId")
                        .IsUnique()
                        .HasFilter("balance_reservation_operation_id IS NOT NULL");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LeavePolicyVersionId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("OrgUnitId", "Status");

                    b.HasIndex("UserId", "StartDate", "EndDate", "Status");

                    b.ToTable("leave_requests", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_leave_requests_balance_link_consistency", "(balance_account_id IS NULL AND balance_reservation_operation_id IS NULL) OR (balance_account_id IS NOT NULL AND balance_reservation_operation_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_leave_requests_calculated_positive", "calculated_days IS NULL OR calculated_days > 0");

                            t.HasCheckConstraint("ck_leave_requests_date_range", "end_date >= start_date");

                            t.HasCheckConstraint("ck_leave_requests_day_portion", "day_portion IN ('FULL_DAY','HALF_DAY')");

                            t.HasCheckConstraint("ck_leave_requests_half_day_single_date", "day_portion <> 'HALF_DAY' OR start_date = end_date");

                            t.HasCheckConstraint("ck_leave_requests_status", "status IN ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','CANCELLATION_REQUESTED','CANCELLED','REVOKED','COMPLETED')");

                            t.HasCheckConstraint("ck_leave_requests_submission_consistency", "(status = 'DRAFT' AND leave_policy_version_id IS NULL AND calculated_days IS NULL AND submitted_at_utc IS NULL AND balance_account_id IS NULL) OR (status <> 'DRAFT' AND leave_policy_version_id IS NOT NULL AND calculated_days IS NOT NULL AND submitted_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("leave_types", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_leave_types_sort_order_non_negative", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("working_calendars", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendarException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("WorkingCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("working_calendar_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkingCalendarId", "Date")
                        .IsUnique();

                    b.ToTable("working_calendar_exceptions", "licenses");
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendarWeekday", b =>
                {
                    b.Property<Guid>("WorkingCalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("working_calendar_id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_working_day");

                    b.HasKey("WorkingCalendarId", "DayOfWeek");

                    b.ToTable("working_calendar_weekdays", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_working_calendar_weekdays_day_of_week", "day_of_week BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.Organization.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("org_units", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_org_units_not_own_parent", "parent_id IS NULL OR parent_id <> id");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.Organization.UserOrgAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from_utc");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_to_utc");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_unit_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("is_primary = true AND effective_to_utc IS NULL");

                    b.HasIndex("UserId", "OrgUnitId", "EffectiveFromUtc")
                        .IsUnique();

                    b.ToTable("user_org_assignments", "licenses", t =>
                        {
                            t.HasCheckConstraint("ck_user_org_assignments_valid_period", "effective_to_utc IS NULL OR effective_to_utc > effective_from_utc");
                        });
                });

            modelBuilder.Entity("Licenses.Domain.Authorization.RolePermission", b =>
                {
                    b.HasOne("Licenses.Domain.Authorization.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.Authorization.RoleScopeAssignment", b =>
                {
                    b.HasOne("Licenses.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.BalanceAccount", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.BalanceBucket", null)
                        .WithMany()
                        .HasForeignKey("BalanceBucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.BalanceLedgerEntry", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.BalanceAccount", null)
                        .WithMany()
                        .HasForeignKey("BalanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeavePolicy", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeavePolicyVersion", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.BalanceBucket", null)
                        .WithMany()
                        .HasForeignKey("BalanceBucketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Licenses.Domain.LeaveManagement.LeavePolicy", null)
                        .WithMany("Versions")
                        .HasForeignKey("LeavePolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.LeaveManagement.WorkingCalendar", null)
                        .WithMany()
                        .HasForeignKey("WorkingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeaveRequest", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.BalanceAccount", null)
                        .WithMany()
                        .HasForeignKey("BalanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.LeaveManagement.LeavePolicyVersion", null)
                        .WithMany()
                        .HasForeignKey("LeavePolicyVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Licenses.Domain.LeaveManagement.LeaveType", null)
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendarException", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.WorkingCalendar", null)
                        .WithMany("Exceptions")
                        .HasForeignKey("WorkingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendarWeekday", b =>
                {
                    b.HasOne("Licenses.Domain.LeaveManagement.WorkingCalendar", null)
                        .WithMany("Weekdays")
                        .HasForeignKey("WorkingCalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.Organization.OrgUnit", b =>
                {
                    b.HasOne("Licenses.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Licenses.Domain.Organization.UserOrgAssignment", b =>
                {
                    b.HasOne("Licenses.Domain.Organization.OrgUnit", null)
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Licenses.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.LeavePolicy", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Licenses.Domain.LeaveManagement.WorkingCalendar", b =>
                {
                    b.Navigation("Exceptions");

                    b.Navigation("Weekdays");
                });
#pragma warning restore 612, 618
        }
    }
}
